title: Lesinwa David
logo: Lesinwa.jpeg
description: A data analyst with experience of using excel for Data analysis, sql for data interrogation and manipulation and power bi for creating business intelligent report. 
show_downloads: true 
google_analytics: 
theme: jekyll-theme-minimal
